apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: {{ .Values.service.loadbalancer}}
  selector:
    # labels are used for selector
    project: roboshop
    purpose: poc
    component: frontend
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port